### ISSUE TITLE
Markdown example in docs doesn't handle slide breaks properly

### ISSUE THREAD

**Issue by joachim-n** [hakimel/reveal.js#2850]
I installed this using the Basic Setup steps here: https://revealjs.com/installation/

I then edited the index.html to try using Markdown. I used the sample code at the top of https://revealjs.com/markdown/ like this:

```
	<body>
		<div class="reveal">
			<div class="slides">
        <section data-markdown>
          <textarea data-template>
            ## Slide 1
            A paragraph with some text and a [link](http://hakim.se).
            ---
            ## Slide 2
            ---
            ## Slide 3
          </textarea>
        </section>
        <section>Slide 2</section>
			</div>
		</div>
```

Expected result is that I get 3 slides made from markdown -- since the sample code says slide 1, slide 2, etc. Instead, all the markdown content shows on a single slide.

**Comment by ee0s** [comment]
I guess the example should read 
```<section data-markdown data-separator="---">```
which is correct in the https://github.com/hakimel/reveal.js/blob/master/examples/markdown.html now.

**Comment by ee0s** [comment]
To be more accurate, https://github.com/hakimel/reveal.js/blob/master/examples/markdown.html has more examples on the use of separators with inline markdown, the last of which says ```No "extra" slides, since there are no separators defined``` and works like the example on https://revealjs.com/markdown/

```                <!-- Use external markdown resource, separate slides by three newlines; vertical slides by two newlines -->
                <section data-markdown="markdown.md" data-separator="^\n\n\n" data-separator-vertical="^\n\n"></section>

                <!-- Slides are separated by three dashes (quick 'n dirty regular expression) -->
                <section data-markdown data-separator="---">
                    <script type="text/template">
                        ## Demo 1
                        Slide 1
                        ---
                        ## Demo 1
                        Slide 2
                        ---
                        ## Demo 1
                        Slide 3
                    </script>
                </section>

                <!-- Slides are separated by newline + three dashes + newline, vertical slides identical but two dashes -->
                <section data-markdown data-separator="^\n---\n$" data-separator-vertical="^\n--\n$">
                    <script type="text/template">
                        ## Demo 2
                        Slide 1.1

                        --

                        ## Demo 2
                        Slide 1.2

                        ---

                        ## Demo 2
                        Slide 2
                    </script>
                </section>

                <!-- No "extra" slides, since there are no separators defined (so they'll become horizontal rulers) -->
                <section data-markdown>
                    <script type="text/template">
                        A

                        ---

                        B

                        ---

                        C
                    </script>
                </section>```

**Comment by hakimel** [comment]
I've pushed a fix for this—slide separation using the default separator should work even if a `data-separator` is not provided.

Until this is released, the best fix is what @ee0s suggested: `<section data-markdown data-separator="---">`

**Comment by pythononwheels** [comment]
Hi, I think this is still not working as expected. Since the code in the example on: [https://revealjs.com/markdown/](https://revealjs.com/markdown/)

`<section data-markdown>
  <textarea data-template>
    ## Slide 1
    A paragraph with some text and a [link](https://hakim.se).
    ---
    ## Slide 2
    ---
    ## Slide 3
  </textarea>
</section>`

Still leads to all slides shown on one page.

I use the Basic installation. (see: [https://revealjs.com/installation/](https://revealjs.com/installation/))

And downloaded the zip from: [ https://github.com/hakimel/reveal.js/archive/master.zip]( https://github.com/hakimel/reveal.js/archive/master.zip)

After adding the 
`data-separator="---"`

everything works as expected.
