### ISSUE TITLE
Wrong Typescript typing for keyboard config option

### ISSUE THREAD

**Issue by steffen-mueller** [hakimel/reveal.js#3749]
Hey there!

The type definition for the `keyboard` option in the `Reveal.Options` interface does not match its real use. In the type definition, its just a boolean, while in the [documentation](https://revealjs.com/keyboard/) and the real life, it is a map of key codes to callbacks or null.

Not a big thing, but would be nice if it was fixed.

**Comment by alishermaan** [comment]
it should be fixed
👋👋👋👋👋👋👋👋

**Comment by steffen-mueller** [comment]
Just as a headsup, `null` is still not accepted with the new reveal types. Tested in 6.0.1.
